# Set update schedule for GitHub Actions

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"  # This covers the root directory
    open-pull-requests-limit: 5
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[github]"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/.github/actions/setup_cache"  # Tracks the .github/actions/setup_cache directory
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[github]"
      include: "scope"

  - package-ecosystem: "docker"
    directory: ".devcontainer"
    open-pull-requests-limit: 3
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[github]"
      include: "scope"

